name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Checkout del repositorio
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      # Configurar Node 22
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      # Limpiar y reinstalar dependencias
      - name: Clean and Install Dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install -g npm@latest
          npm install
        working-directory: ./frontend

      # Construir la app
      - name: Build App
        run: npm run build
        working-directory: ./frontend

      # Desplegar a Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          output_location: "frontend/dist"
