name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1️⃣ Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node 22
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.17.0'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend   # <-- ajustá si tu frontend está en otra carpeta

      # 4️⃣ Build del proyecto
      - name: Build project
        run: npm run build
        working-directory: ./frontend

      # 5️⃣ Deploy a Azure Static Web App
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"      # ruta de tu app
          api_location: ""              # si tenés Azure Functions, pon la ruta; sino ""
          output_location: "dist"       # carpeta generada por Vite
