# .github/workflows/deploy.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Cambiá por tu rama de producción
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend   # <-- carpeta de tu package-lock.json
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npx vite build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"          # <-- donde está tu código fuente
          output_location: "frontend/dist"  # <-- donde se genera el build
          api_location: ""                  # <-- si no tenés API en Azure Functions
