name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: ./frontend   # <-- carpeta donde está tu package-lock.json
        run: npm ci --include=dev

      # 4. Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npx vite build

      # 5. Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # usado por GitHub Actions
          action: "upload"
          app_location: "frontend"          # tu carpeta de frontend
          output_location: "frontend/dist"  # donde genera Vite los archivos estáticos
